language: node_js
node_js:
- '4'
deploy:
  provider: heroku
  api_key:
    secure: G2jUzF9HArQrxnPbtFhiRaoDGButkGAimeUrmNvsjjIMBEfzktWejtER2nQQbji+pHM9l0ErXpQjnqdNn7MxxbJ9Qmt+AhQp/7yFBUBm3j0njL2gk7vHMVaY3w8/XdhK9JK85aLoCqpoQHrmJbYD/TeLnnZnKGFFbupCEN5HLuBM3AFRl77O4TmpPWQguQ+lFoSxy8TmRnoepHZq5OW8O7xvS/WD0tgewxq/t+pcGX7YndZTampnpkcqXSiHWL4dFQv48XoSEgluuRx/YBp2mltU89A6g2SRbO6/xf6xywMPvVuhYjs4IbQ1YnObr2L7cbUyP4WAizU2OvxWIwfs5/vyHmB99ldNxe2v7I+k4abi+zY6mMtAmgRL42ux2WQT8zxq4NDXLf+Ha03+cC2CiYMp9WEpEPoMbMFgyIleJv2mii4fKUMMaV7jjHRWYV9smFqywGJHfjEeAIkILvNreD8sff15N1Cw81P1ex0J93UK1AfYsoSDGeqV0jMuKsXD3rdoHyI2McOP8aTvnt68Y8NBOCxLlHg+ttyTA5ULykXypiy8PVsyIXsBWv+hcRj72SvNkpL2i661Gn4lCZzP7dygjAQRAzm9BQ+1nPg4thSwDcgeT40wjl7jtI5oSeKbMwHJsaXVy+bbxpOz2cdyL6yxSEIGHG0Obik4c92tXPs=
